package stars

var names = []string{
	"Acamar",
	"Achird",
	"Acrab",
	"Acrux",
	"Acubens",
	"Adhafera",
	"Adhara",
	"Ain",
	"Aladfar",
	"Alamak",
	"Alathfar",
	"Albaldah",
	"Albali",
	"Albireo",
	"Alchiba",
	"Alcyone",
	"Alderamin",
	"Aldhafera",
	"Aldhanab",
	"Aldhibah",
	"Al Fawaris",
	"Alfecca Meridiana",
	"Alfirk",
	"Algedi",
	"Algenib",
	"Algieba",
	"Al Giedi",
	"Algorab",
	"Alhena",
	"Alioth",
	"Alkaid",
	"Al Kalb al Rai",
	"Alkalurops",
	"Al Kaphrah",
	"Alkes",
	"Alkurah",
	"Almach",
	"Almagest",
	"Al Minliar al Asad",
	"Al Nair",
	"Alnilam",
	"Alnitak",
	"Alniyat",
	"Al Niyat",
	"Alpha Andromedae",
	"Alpha Antliae",
	"Alpha Apodis",
	"Alpha Aquarii",
	"Alpha Aquilae",
	"Alpha Arae",
	"Alpha Arianni",
	"Alpha Arietis",
	"Alpha Aurigae",
	"Alpha Bootis",
	"Alpha Brahe",
	"Alpha Caeli",
	"Alpha Camelopardalis",
	"Alpha Cancri",
	"Alpha Capricorni",
	"Alpha Carinae",
	"Alpha Cassiopeiae",
	"Alpha Centauri",
	"Alpha Cephei",
	"Alpha Cerenkov",
	"Alpha Ceti",
	"Alpha Chamaeleonis",
	"Alpha Chandrasekhar",
	"Alpha Circini",
	"Alpha Columbae",
	"Alpha Copernicus",
	"Alpha Corvi",
	"Alpha Crateris",
	"Alpha Crucis",
	"Alpha Cygnus",
	"Alpha Delphini",
	"Alpha Doradus",
	"Alpha Draconis",
	"Alpha Equulei",
	"Alpha Eridani",
	"Alpha Fornacis",
	"Alpha Geminorum",
	"Alpha Giclas",
	"Alpha Gorno",
	"Alpha Gruis",
	"Alpha Herculis",
	"Alpha Horologii",
	"Alpha Hyades",
	"Alpha Hydrae",
	"Alpha Hyginus",
	"Alpha Illuminati",
	"Alpha Indi",
	"Alpha Kepler",
	"Alpha Klystron",
	"Alpha Krueger",
	"Alpha Lacaille",
	"Alpha Lacertae",
	"Alpha Lalande",
	"Alpha Lentilis",
	"Alpha Leonis",
	"Alpha Leporis",
	"Alpha Librae",
	"Alpha Lipi",
	"Alpha Luyten",
	"Alpha Lyncis",
	"Alpha Lyrae",
	"Alpha Maksutov",
	"Alpha Mensae",
	"Alpha Mersenne",
	"Alpha Mira",
	"Alpha Monocerotis",
	"Alpha Muscae",
	"Alpha Normae",
	"Alpha Octantis",
	"Alpha Ophiuchi",
	"Alpha Orionis",
	"Alpha Pavonis",
	"Alpha Pegasi",
	"Alpha Persei",
	"Alpha Phoenicis",
	"Alpha Pictoris",
	"Alpha Piscium",
	"Alpha Ptolemae",
	"Alpha Puppis",
	"Alpha Pyxidis",
	"Alpha Raynet",
	"Alphard",
	"Alpha Reticuli",
	"Alpha Sagittae",
	"Alpha Sagittarii",
	"Alpha Saurus",
	"Alpha Scorpii",
	"Alpha Sculptoris",
	"Alpha Scuti",
	"Alpha Serpentis",
	"Alpha Sextantis",
	"Alpha Tauri",
	"Alpha Telescopii",
	"Alpha Trianguli",
	"Alpha Tucanae",
	"Alpha Velorum",
	"Alpha Virginis",
	"Alpha Vitalis",
	"Alpha Volantis",
	"Alpha Vulpeculae",
	"Alpha Wolf",
	"Alphecca",
	"Alpheratz",
	"Alpher Olber",
	"Alrai",
	"Alrakis",
	"Alrischa",
	"Alsafi",
	"Alschain",
	"Alsciaukat",
	"Alshat",
	"Altais",
	"Altarf",
	"Alterf",
	"Al Thalimain",
	"Aludra",
	"Alula Australis",
	"Alula Borealis",
	"Alwaid",
	"Alya",
	"Alzir",
	"Ancha",
	"Angetenar",
	"Ankaa",
	"Arcturus",
	"Arkab",
	"Arkab Posterior",
	"Arkab Prior",
	"Arm",
	"Arneb",
	"Arrakis",
	"Ascella",
	"Asellus Australis",
	"Asellus Borealis",
	"Asellus Primus",
	"Asellus Secundus",
	"Asellus Tertius",
	"Ashlesha",
	"Askella",
	"Aspidiske",
	"Asterion",
	"Asterope",
	"Atik",
	"Atlas",
	"Atria",
	"Avior",
	"Azaleh",
	"Azelfafage",
	"Azha",
	"Azmidiske",
	"Baham",
	"Barnard's Star",
	"Baten Kaitos",
	"Becrux",
	"Beid",
	"Bellatrix",
	"Benetnasch",
	"Beta Andromedae",
	"Beta Antliae",
	"Beta Apodis",
	"Beta Aquarii",
	"Beta Aquilae",
	"Beta Arae",
	"Beta Arianni",
	"Beta Arietis",
	"Beta Aurigae",
	"Beta Bootis",
	"Beta Brahe",
	"Beta Caeli",
	"Beta Camelopardalis",
	"Beta Cancri",
	"Beta Capricorni",
	"Beta Carinae",
	"Beta Cassiopeiae",
	"Beta Centauri",
	"Beta Cephei",
	"Beta Cerenkov",
	"Beta Ceti",
	"Beta Chamaeleonis",
	"Beta Chandrasekhar",
	"Beta Circini",
	"Beta Columbae",
	"Beta Copernicus",
	"Beta Corvi",
	"Beta Crateris",
	"Beta Crucis",
	"Beta Cygnus",
	"Beta Delphini",
	"Beta Doradus",
	"Beta Draconis",
	"Beta Equulei",
	"Beta Eridani",
	"Beta Fornacis",
	"Beta Geminorum",
	"Beta Giclas",
	"Beta Gorno",
	"Beta Gruis",
	"Beta Herculis",
	"Beta Horologii",
	"Beta Hyades",
	"Beta Hydrae",
	"Beta Hygines",
	"Beta Illuminati",
	"Beta Indi",
	"Beta Kepler",
	"Beta Klystron",
	"Beta Krueger",
	"Beta Lacaille",
	"Beta Lacertae",
	"Beta Lalande",
	"Beta Lentilis",
	"Beta Leonis",
	"Beta Leporis",
	"Beta Librae",
	"Beta Lipi",
	"Beta Luyten",
	"Betal Vitalis",
	"Beta Lyncis",
	"Beta Lyrae",
	"Beta Maksutov",
	"Beta Mensae",
	"Beta Mersenne",
	"Beta Mira",
	"Beta Monocerotis",
	"Beta Muscae",
	"Beta Normae",
	"Beta Octantis",
	"Beta Olber",
	"Beta Ophiuchi",
	"Beta Orionis",
	"Beta Pavonis",
	"Beta Pegasi",
	"Beta Persei",
	"Beta Phoenicis",
	"Beta Pictoris",
	"Beta Piscium",
	"Beta Ptolemae",
	"Beta Puppis",
	"Beta Pyxidis",
	"Beta Raynet",
	"Beta Reticuli",
	"Beta Sagittae",
	"Beta Sagittarii",
	"Beta Saurus",
	"Beta Scorpii",
	"Beta Sculptoris",
	"Beta Scuti",
	"Beta Serpentis",
	"Beta Sextantis",
	"Beta Tauri",
	"Beta Telescopii",
	"Beta Trianguli",
	"Beta Tucanae",
	"Beta Velorum",
	"Beta Virginis",
	"Beta Volantis",
	"Beta Vulpeculae",
	"Beta Wolf",
	"Betria",
	"Bharani",
	"Birdun",
	"Bogardus",
	"Botein",
	"Brachium",
	"Bunda",
	"Caph",
	"Castor",
	"Cebalrai",
	"Celaeno",
	"Chara",
	"Cheleb",
	"Chertan",
	"Chort",
	"Chow",
	"Cor Caroli",
	"Cursa",
	"Dabih",
	"Decrux",
	"Delta Antliae",
	"Delta Apodis",
	"Delta Aquarii",
	"Delta Aquilae",
	"Delta Arae",
	"Delta Arietis",
	"Delta Aurigae",
	"Delta Bootis",
	"Delta Brahe",
	"Delta Caeli",
	"Delta Camelopardalis",
	"Delta Cancri",
	"Delta Cassiopeiae",
	"Delta Centauri",
	"Delta Ceti",
	"Delta Chamaeleonis",
	"Delta Chandrasekhar",
	"Delta Circini",
	"Delta Corvi",
	"Delta Crateris",
	"Delta Crucis",
	"Delta Cygnus",
	"Delta Draconis",
	"Delta Fornacis",
	"Delta Geminorum",
	"Delta Giclas",
	"Delta Gorno",
	"Delta Gruis",
	"Delta Horologii",
	"Delta Hyades",
	"Delta Illuminati",
	"Delta Krueger",
	"Delta Lalande",
	"Delta Lentilis",
	"Delta Librae",
	"Delta Lipi",
	"Delta Lyncis",
	"Delta Mira",
	"Delta Muscae",
	"Delta Normae",
	"Delta Orionis",
	"Delta Persei",
	"Delta Pictoris",
	"Delta Piscium",
	"Delta Ptolemae",
	"Delta Reticuli",
	"Delta Sagittarii",
	"Delta Scorpii",
	"Delta Sculptoris",
	"Delta Scuti",
	"Delta Serpentis",
	"Delta Sextantis",
	"Delta Tauri",
	"Delta Virginis",
	"Delta Vitalis",
	"Delta Volantis",
	"Delta Vulpeculae",
	"Deneb Algedi",
	"Deneb Dulfim",
	"Deneb el Okab",
	"Deneb Kaitos",
	"Deneb Kaitos Schemali",
	"Denebola",
	"Dheneb",
	"Diadem",
	"Diphda",
	"Dnoces",
	"Dschubba",
	"Dubhe",
	"Duhr",
	"Edasich",
	"Electra",
	"Elmuthalleth",
	"Elnath",
	"Eltanin",
	"Enif",
	"Epilson Fornacis",
	"Epsilon Antliae",
	"Epsilon Aquarii",
	"Epsilon Aquilae",
	"Epsilon Arae",
	"Epsilon Ariestis",
	"Epsilon Bootis",
	"Epsilon Brahe",
	"Epsilon Caeli",
	"Epsilon Camelopardalis",
	"Epsilon Cassiopeiae",
	"Epsilon Centauri",
	"Epsilon Ceti",
	"Epsilon Chamaeleonis",
	"Epsilon Chandrasekhar",
	"Epsilon Circini",
	"Epsilon Corvi",
	"Epsilon Crateris",
	"Epsilon Cygnus",
	"Epsilon Draconis",
	"Epsilon Giclas",
	"Epsilon Gruis",
	"Epsilon Horologii",
	"Epsilon Hyades",
	"Epsilon Illuminati",
	"Epsilon Krueger",
	"Epsilon Librae",
	"Epsilon Lipi",
	"Epsilon Lyncis",
	"Epsilon Muscae",
	"Epsilon Normae",
	"Epsilon Orionis",
	"Epsilon Persei",
	"Epsilon Ptolemae",
	"Epsilon Scorpii",
	"Epsilon Sculptoris",
	"Epsilon Scuti",
	"Epsilon Serpentis",
	"Epsilon Sextantis",
	"Epsilon Tauri",
	"Epsilon Volantis",
	"Epsilon Vulpeculae",
	"Errai",
	"Eta Aquarii",
	"Eta Bootis",
	"Eta Camelopardalis",
	"Eta Ceti",
	"Eta Chamaeleonis",
	"Eta Corvi",
	"Eta Crateris",
	"Eta Draconis",
	"Eta Fornacis",
	"Eta Giclas",
	"Eta Gruis",
	"Eta Horologii",
	"Eta Hyades",
	"Eta Illuminati",
	"Eta Librae",
	"Eta Lyncis",
	"Etamin",
	"Eta Orionis",
	"Eta Persei",
	"Eta Ptolemae",
	"Eta Serpentis",
	"Eta Volantis",
	"Eta Vulpeculae",
	"Fum al Samakah",
	"Furud",
	"Gacrux",
	"Gamma Antliae",
	"Gamma Apodis",
	"Gamma Aquarii",
	"Gamma Aquilae",
	"Gamma Arae",
	"Gamma Arianni",
	"Gamma Arietis",
	"Gamma Aurigae",
	"Gamma Bootis",
	"Gamma Brahe",
	"Gamma Caeli",
	"Gamma Camelopardalis",
	"Gamma Cancri",
	"Gamma Capricorni",
	"Gamma Carinae",
	"Gamma Cassiopeiae",
	"Gamma Centauri",
	"Gamma Ceti",
	"Gamma Chamaeleonis",
	"Gamma Chandrasekhar",
	"Gamma Circini",
	"Gamma Columbae",
	"Gamma Copernicus",
	"Gamma Corvi",
	"Gamma Crateris",
	"Gamma Crucis",
	"Gamma Cygnus",
	"Gamma Draconis",
	"Gamma Eridani",
	"Gamma Fornacis",
	"Gamma Geminorum",
	"Gamma Giclas",
	"Gamma Gorno",
	"Gamma Gruis",
	"Gamma Horologii",
	"Gamma Hyades",
	"Gamma Hydrae",
	"Gamma Illuminati",
	"Gamma Kepler",
	"Gamma Krueger",
	"Gamma Lacaille",
	"Gamma Lalande",
	"Gamma Lentilis",
	"Gamma Leonis",
	"Gamma Leporis",
	"Gamma Librae",
	"Gamma Lipi",
	"Gamma Luyten",
	"Gamma Lyncis",
	"Gamma Mensae",
	"Gamma Mira",
	"Gamma Muscae",
	"Gamma Normae",
	"Gamma Olber",
	"Gamma Ophiuchi",
	"Gamma Orionis",
	"Gamma Persei",
	"Gamma Phoenicis",
	"Gamma Pictoris",
	"Gamma Piscium",
	"Gamma Ptolemae",
	"Gamma Puppis",
	"Gamma Pyxidis",
	"Gamma Raynet",
	"Gamma Reticuli",
	"Gamma Sagittae",
	"Gamma Sagittarii",
	"Gamma Saurus",
	"Gamma Scorpii",
	"Gamma Sculptoris",
	"Gamma Scuti",
	"Gamma Serpentis",
	"Gamma Sextantis",
	"Gamma Tauri",
	"Gamma Telescopii",
	"Gamma Trianguli",
	"Gamma Tucanae",
	"Gamma Virginis",
	"Gamma Vitalis",
	"Gamma Volantis",
	"Gamma Vulpeculae",
	"Garnet Star",
	"Gatria",
	"Gianfar",
	"Giedi",
	"Gienah Gurab",
	"Giennah",
	"Girtab",
	"Gomeisa",
	"Gorgonea Tertia",
	"Gorno Epsilon",
	"Graffias",
	"Grafias",
	"Grassias",
	"Groombridge",
	"Grumium",
	"Hadar",
	"Hadir",
	"Haedus",
	"Haldus",
	"Hamal",
	"Hassaleh",
	"Head of Hydrus",
	"Heka",
	"Heze",
	"Hoedus I",
	"Hoedus II",
	"Homam",
	"Hyadum I",
	"Hyadum II",
	"Hydrobius",
	"Hyperion",
	"Iota Camelopardalis",
	"Iota Chamaeleonis",
	"Iota Draconis",
	"Iota Horologii",
	"Iota Hyades",
	"Iota Orionis",
	"Iota Persei",
	"Iota Serpentis",
	"Izar",
	"Jabbah",
	"Jih",
	"Kaffaljidhm",
	"Kajam",
	"Kappa Chamaeleonis",
	"Kappa Draconis",
	"Kappa Horologii",
	"Kappa Hyades",
	"Kappa Orionis",
	"Kastra",
	"Kaus Australis",
	"Kaus Borealis",
	"Kaus Medius",
	"Keid",
	"Kitalpha",
	"Kochab",
	"Kornephoros",
	"Kraz",
	"Ksora",
	"Kullat Nunu",
	"Kuma",
	"Lambda Draconis",
	"Lambda Horologii",
	"Lambda Orionis",
	"Lamdba Hyades",
	"Lanx Australis",
	"La Superba",
	"Lesath",
	"Lucida",
	"Lucida Anseris",
	"Luyten's Star",
	"Maasym",
	"Mahasim",
	"Maia",
	"Marfark",
	"Marfik",
	"Markab",
	"Matar",
	"Mebsuta",
	"Media",
	"Megrez",
	"Meissa",
	"Mekbuda",
	"Menchib",
	"Menkab",
	"Menkalinan",
	"Menkar",
	"Menkent",
	"Menkib",
	"Merak",
	"Merga",
	"Merope",
	"Mesarthim",
	"Metis",
	"Miaplacidus",
	"Microscopii",
	"Mimosa",
	"Minchir",
	"Minelava",
	"Minkar",
	"Mintaka",
	"Mira",
	"Mirach",
	"Miram",
	"Mirfak",
	"Mirzam",
	"Misam",
	"Mothallah",
	"Mu Draconis",
	"Muliphein",
	"Mu Orionis",
	"Muphrid",
	"Murzim",
	"Muscida",
	"Nair Al Saif",
	"Naos",
	"Nash",
	"Nashira",
	"Navi",
	"Nekkar",
	"Neshmet",
	"Nihal",
	"Nu Draconis",
	"Nunki",
	"Nusakan",
	"Okul",
	"Organon",
	"Peacock",
	"Phact",
	"Phad",
	"Pherkad",
	"Pherkard",
	"Pleione",
	"Polaris",
	"Polaris Australis",
	"Pollux",
	"Porrima",
	"Praecipua",
	"Propus",
	"Proxima Centauri",
	"Pulcherrima",
	"Rana",
	"Rasalas",
	"Ras Algethi",
	"Ras Alhague",
	"Ras Elased Australis",
	"Rastaban",
	"Regor",
	"Rigel",
	"Rigil Kentaurus",
	"Rijl al Awwa",
	"Rotanev",
	"Ruchba",
	"Ruchbah",
	"Rukbat",
	"Rukh",
	"Sabik",
	"Sadachbia",
	"Sadalbari",
	"Sadalmelik",
	"Sadalsuud",
	"Sadatoni",
	"Sadira",
	"Sadr",
	"Saiph",
	"Salm",
	"Sargas",
	"Sarin",
	"Sarir",
	"Sasin",
	"Sceptrum",
	"Scheat",
	"Schedar",
	"Scheddi",
	"Segin",
	"Seginus",
	"Sham",
	"Shaula",
	"Sheliak",
	"Sheratan",
	"Situla",
	"Skat",
	"Spica",
	"Squidi Alpha",
	"Squidi Beta",
	"Squidi Gamma",
	"Sterope II",
	"Sualocin",
	"Subra",
	"Suhail",
	"Sulafat",
	"Syrma",
	"Tabit",
	"Talitha Australis",
	"Talitha Borealis",
	"Tania Australis",
	"Tania Borealis",
	"Tarazet or Tarazed",
	"Tau Ceti",
	"Taygeta",
	"Tegmen",
	"Tejat Posterior",
	"Tejat Prior",
	"Terebellum",
	"Thabit",
	"Theemin",
	"Theta Camelopardalis",
	"Theta Chamaeleonis",
	"Theta Crateris",
	"Theta Draconis",
	"Theta Giclas",
	"Theta Horologii",
	"Theta Hyades",
	"Theta Illuminati",
	"Theta Lyncis",
	"Theta Orionis",
	"Theta Persei",
	"Theta Serpentis",
	"Thuban",
	"Tien Kuan",
	"Toliman",
	"Torcularis Septemtrionalis",
	"Tseen Kee",
	"Tsih",
	"Tureis",
	"Tyl",
	"Unuk",
	"Van Maanen's star",
	"Vega",
	"Vela",
	"Vindemiatrix",
	"Wasat",
	"Wazn",
	"Wei",
	"Wezen",
	"Xi Draconis",
	"Yed Posterior",
	"Yed Prior",
	"Yildun",
	"Zaniah",
	"Zaurak",
	"Zavijava",
	"Zeeman",
	"Zeta Antliae",
	"Zeta Aquarii",
	"Zeta Bootis",
	"Zeta Brahe",
	"Zeta Camelopardalis",
	"Zeta Centauri",
	"Zeta Ceti",
	"Zeta Chamaeleonis",
	"Zeta Circini",
	"Zeta Corvi",
	"Zeta Crateris",
	"Zeta Draconis",
	"Zeta Fornacis",
	"Zeta Giclas",
	"Zeta Gruis",
	"Zeta Horologii",
	"Zeta Hyades",
	"Zeta Illuminati",
	"Zeta Krueger",
	"Zeta Librae",
	"Zeta Lyncis",
	"Zeta Muscae",
	"Zeta Normae",
	"Zeta Oionis",
	"Zeta Persei",
	"Zeta Ptolemae",
	"Zeta Reticulii",
	"Zeta Scorpii",
	"Zeta Scuti",
	"Zeta Serpentis",
	"Zeta Sextantis",
	"Zeta Tauri",
	"Zeta Volantis",
	"Zeta Vulpeculae",
	"Zosma",
	"Zuben-el-Akrab",
	"Zuben-el-Akribi",
	"Zubenelgenubi",
	"Zubeneschamali",
}
